config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEG = ['chinese', 'italian', 'japanese', 'french','belgian']
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEG }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: :show
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def show
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [:new, :create]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- app/views/layouts/application.html.erb -->
    <head>
      <!-- Add these line for detecting device width -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

      <!-- [...] -->
    </head>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container">
    <%= simple_form_for(@restaurant, html: { class: 'form-inline' }) do |f| %>
      <div class="form-group">
        <%= f.input :name %>
      </div>
      <div class="form-group">
        <%= f.input :address %>
      </div>
      <div class="form-group">
        <%= f.input :category, collection: Restaurant::CATEG %>
      </div>
      <div class="form-group">
        <%= f.input :phone_number %>
      </div>
      <%= f.submit class: "btn btn-success" %>
    <% end %>
  </div>

<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<h1> Restaurants 🍽</h1>
<% @restaurants.each do |restaurant| %>

<h2>

  <%= link_to restaurant.name, restaurant_path(restaurant) %>
</h2>
<h4>
  <%= restaurant.address %>
  (<%= restaurant.category %>)
  </h4>
<% end %>
<%= link_to 'Create a new Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= render 'form'  %>

app/views/restaurants/show.html.erb
<h1>
  <%= @restaurant.name %>
  (<%= @restaurant.category %>)

</h1>
<h5>
  <%= @restaurant.address %>
  <%= @restaurant.phone_number %>
</h5>
<% @restaurant.reviews.each do |review| %>
<p>
  <%= '⭐️' * review.rating %>
</p>
<% end %>

<%= link_to 'Back to Restaurants', root_path %>
<p><%= link_to 'Write a review', new_restaurant_review_path(@restaurant) %></p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit %>
<% end %>